In [1]:
# Disable jedi autocompleter
%config Completer.use_jedi = False

%load_ext autoreload
%autoreload 2

import numpy as np
import torch
import gym
import os
# os.path.dirname(os.path.realpath(__file__))


env = gym.make('gym_kinova_gripper:kinovagripper-v0')

/home/mechagodzilla/kinova_venv/lib/python3.6/site-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))


In [2]:
import os
# os.path.dirname(os.path.realpath(__file__))

In [3]:


env = gym.make('gym_kinova_gripper:kinovagripper-v0')

# for i in range(100):
#     env.render()
    
# env.close() # broken

running build_ext


/home/mechagodzilla/kinova_venv/lib/python3.6/site-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))


In [98]:
# obs = env.reset(shape_keys=['CylinderM'], hand_orientation='normal')  # TODO: make sure this is NO OBJECT
# env.render()

In [99]:
# env.close()

# # next: control starting position
# obs = env.reset(shape_keys=['CylinderM'], hand_orientation='normal', start_pos=[0.1, 0.0, 0.0])  # TODO: make sure this is NO OBJECT
# env.render()

In [4]:
env.close()
# next: control hand position
roll_noise, pitch_noise, yaw_noise = 0, 0, 0

# roll_noise = np.pi / 6  # wrist go uppy
pitch_noise = np.pi / 6

obs = env.reset(shape_keys=['CylinderM'], hand_orientation='normal',
                start_pos=[0.0, 0.0, 0.0], hand_rotation=[-1.57 + roll_noise, 0 + pitch_noise, -1.57])  # TODO: make sure this is NO OBJECT
# env.render()

# note: simulator doesn't rotate around the point 0 0 0 either... we'll need to fix that

selecting object...
going into experiment function
EXPERIMENT FUNCTION before
{}
['CylinderM']
EXPERIMENT FUNCTION
{'CylinderM': '/kinova_description/j2s7s300_end_effector_v1_CylinderM.xml'}
['CylinderM']
hi, what could go wrong
FILENAME objects_file_to_list:  NONOfNOobjects.csv
shape keys: ['CylinderM']
the filepath is: NONOfNOobjects.csv
THE FILENAME DOESNT EXIST
IM GENERATING LATIN SQUARES 1036
why the fuck am i entering self.experiment again
SHAPE KEYS: ['CylinderM']
object keys: dict_keys(['CylinderM'])
EXPERIMENT FUNCTION before
{'CylinderM': '/kinova_description/j2s7s300_end_effector_v1_CylinderM.xml'}
['CylinderM']
EXPERIMENT FUNCTION
{'CylinderM': '/kinova_description/j2s7s300_end_effector_v1_CylinderM.xml'}
['CylinderM']
TEMP <= N
TEMP <= N
TEMP <= N
TEMP <= N
TEMP <= N
TEMP <= N
TEMP <= N
TEMP <= N
TEMP <= N
NONOfNOobjects.csv
wtfwtf
wtfwtf
wtfwtf
wtfwtf
wtfwtf
wtfwtf
wtfwtf
wtfwtf
wtfwtf
get the object lol ==========
OUR RANDOM SHAPES BEFOREHAND
['CylinderM', 'CylinderM', '

In [5]:
obs

[-0.011397965081607848,
 0.04114406159453828,
 0.007183614559094081,
 0.08832502113858473,
 0.041294062549291244,
 0.026103854975344343,
 0.08832489500532889,
 0.04129406254980782,
 -0.026168276461965026,
 -0.03947062389920691,
 0.0633973514600787,
 0.013201547542268308,
 0.11654731313670674,
 0.06354735371438014,
 0.03137565419511533,
 0.11654730529100633,
 0.06354735371441224,
 -0.031439442398386315,
 -2.6020852139652106e-18,
 6.071532165918825e-18,
 1.3877787807814457e-17,
 -0.04948116343207048,
 0.07635431311099898,
 -0.06521687715807606,
 -0.0,
 -0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.02037104219198227,
 0.02037104219198227,
 0.10546249896287918,
 0.08434496275729382,
 0.08832539609157548,
 0.16945814334349601,
 0.1631716465375126,
 0.14753980748115775,
 0.14162715233107603,
 0.08072037078709081,
 0.07951780374362612,
 0.2024207899660105,
 0.19494383831966028,
 0.17961462924897525,
 0.17225466764671296,
 0.7068896452650238,
 0.5750008746280698,
 6,
 6,
 6,
 6,
 6,
 0.58

In [6]:
obs[33:36]

[0.02037104219198227, 0.02037104219198227, 0.10546249896287918]

In [7]:
np.array(obs)

array([-1.13979651e-02,  4.11440616e-02,  7.18361456e-03,  8.83250211e-02,
        4.12940625e-02,  2.61038550e-02,  8.83248950e-02,  4.12940625e-02,
       -2.61682765e-02, -3.94706239e-02,  6.33973515e-02,  1.32015475e-02,
        1.16547313e-01,  6.35473537e-02,  3.13756542e-02,  1.16547305e-01,
        6.35473537e-02, -3.14394424e-02, -2.60208521e-18,  6.07153217e-18,
        1.38777878e-17, -4.94811634e-02,  7.63543131e-02, -6.52168772e-02,
       -0.00000000e+00, -0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  2.03710422e-02,  2.03710422e-02,  1.05462499e-01,
        8.43449628e-02,  8.83253961e-02,  1.69458143e-01,  1.63171647e-01,
        1.47539807e-01,  1.41627152e-01,  8.07203708e-02,  7.95178037e-02,
        2.02420790e-01,  1.94943838e-01,  1.79614629e-01,  1.72254668e-01,
        7.06889645e-01,  5.75000875e-01,  6.00000000e+00,  6.00000000e+00,
        6.00000000e+00,  

In [8]:
from utils import state_dim_setup
# finger positions (12), wrist pos (3), obj pos (3), last 6 joint states (6),
# obj size (3), finger obj dist (4)
state_idx_arr = state_dim_setup('adam_sim2real')
np.array(obs)[state_idx_arr]  # might need to do unit conversions

array([ 1.16547313e-01,  6.35473537e-02,  3.13756542e-02,  8.83250211e-02,
        4.12940625e-02,  2.61038550e-02,  1.16547305e-01,  6.35473537e-02,
       -3.14394424e-02,  8.83248950e-02,  4.12940625e-02, -2.61682765e-02,
       -2.60208521e-18,  6.07153217e-18,  1.38777878e-17, -4.94811634e-02,
        7.63543131e-02, -6.52168772e-02,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        2.03710422e-02,  2.03710422e-02,  1.05462499e-01,  7.95178037e-02,
        8.83253961e-02,  1.94943838e-01,  1.63171647e-01])

In [ ]:
# dude.... determine_wrist_pos_coords is fucking hardcoded.

"""
0. plan what I want to rotate my wrist around...
1. add some quaternion code to rotate around a centerpoint 0,0,0.
2. generalizable rotation code..

----- math -----
what we need to solve the problem:
hand position in space
origin axis = 0 0 0
how much we wanna rotate

use scipy for quaternion math

1. find our current orientation
2. find the position in space to rotate around (the axis?)
3. 
"""

In [101]:
from scipy.spatial.transform import Rotation as R

In [ ]:
# position in space
hand_point = [1, 1, 2]
hand_orientation = []

rotation_point = [0, 0, 0]  # rotate around this
rotation_axis = [1, 1, 1]

how_much_rotation = [0, 0, 0]  # in radians: roll, pitch, yaw




# change orientation
hand_orientation = [1, 1, 1]

rotation = R.from_euler('xyz', how_much_rotation)








In [107]:

# rotate along an arbitrary axis instead:
vec = [2,1,1]

rotation_degrees = 90
rotation_radians = np.radians(rotation_degrees)
rotation_axis = np.array([0, 0, 1])

rotation_vector = rotation_radians * rotation_axis
rotation = R.from_rotvec(rotation_vector)
rotated_vec = rotation.apply(vec)
rotated_vec

array([-1.,  2.,  1.])

In [104]:
# a mortal's way: use euler angles
# iirc this rotates around the point 0,0,0

how_much_rotation = [0, 0, np.pi/2]
rotation = R.from_euler('xyz', how_much_rotation)

rotated_vec = rotation.apply(vec)
rotated_vec

array([-1.,  1.,  1.])

In [ ]:
# next: rotate the actual position



In [ ]:
# provide code to rotate around an axis
# provide code

In [108]:
def rotate_around_origin(vec, how_much_rotation):
    # vec: xyz
    # how_much_rotation: in radians. use np.radians to covert if necessary
    # roll, pitch, yaw.
    how_much_rotation = [0, 0, np.pi/2]
    rotation = R.from_euler('xyz', how_much_rotation)

    rotated_vec = rotation.apply(vec)
    return rotated_vec

def rotate_around_axis(vec, theta, axis, input_unit='deg'):
    """
    vec: xyz
    theta: single angle, but now around arbitrary axis
    axis: defined as a 3d vector direction, xyz
    """
    rotation_radians = theta
    
    if input_unit=='deg':
        rotation_radians = np.radians(theta)
    
    rotation_axis = np.array(axis) # type conversion... just in case
    rotation_vector = rotation_radians * rotation_axis
    rotation = R.from_rotvec(rotation_vector)
    rotated_vec = rotation.apply(vec)
    return rotated_vec

In [109]:

rotate_around_origin(vec, how_much_rotation)

array([-1.,  2.,  1.])

In [110]:
rotate_around_axis(vec, 90, [0, 0, 1])

array([-1.,  2.,  1.])

In [ ]:
vec = [0.0, 0.18, 0.0654]
how_much_rotation
rotate_around_origin(vec, how_much_rotation)

In [ ]:
global_rotation_arr = [-np.pi / 2, 0, -np.pi / 2]
global_rot = R.from_euler('xyz', global_rotation_arr)

pain = global_rot.apply([0, 0.18, 0.0654], inverse=True)

In [32]:
list(pain)

[-0.18, -0.0654, 5.4489746048602685e-17]

In [4]:
env.close()
# next: control hand position
roll_noise, pitch_noise, yaw_noise = 0, 0, 0

# roll_noise = np.pi / 6  # wrist go uppy/downy
# pitch_noise = np.pi / 6  # wrist pivot left/right
# yaw_noise = np.pi / 6  # rotate the wrist (wrist twist!!)

# -1.57, 0, -1.57 is the default hand position (for a side grasp)
start_hand_rotation = [-1.57 + roll_noise, 0 + pitch_noise, -1.57 + yaw_noise]
# start_hand_rotation = [0, , 0]

# mappings from start to eulers: 2 => x (1)
# 3 => 2

env = gym.make('gym_kinova_gripper:kinovagripper-v0')  # maybe just make a new one everytime lol

obs = env.reset(shape_keys=['CubeM'], hand_orientation='normal',
                start_pos=[0.0, 0.0, 0.0], hand_rotation=start_hand_rotation)  # TODO: make sure this is NO OBJECT
while True:
    env.render()

# note: simulator doesn't rotate around the point 0 0 0 either... we'll need to fix that

NameError: name 'env' is not defined

In [39]:
OLD
[[-9.99999683e-01 -6.34136231e-07  7.96326458e-04  2.00454847e-03]
 [ 3.35742702e-16 -9.99999683e-01 -7.96326711e-04  7.11069957e-02]
 [ 7.96326711e-04 -7.96326458e-04  9.99999366e-01 -6.52838842e-02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]

SyntaxError: invalid syntax (<ipython-input-39-c85853237f56>, line 1)

In [ ]:
NEW
[[-9.99999683e-01 -6.34136231e-07  7.96326458e-04 -5.19656058e-05]
 [ 3.35742702e-16 -9.99999683e-01 -7.96326711e-04  7.00520227e-02]
 [ 7.96326711e-04 -7.96326458e-04  9.99999366e-01 -6.52566198e-02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]

In [ ]:
original_point = [0, 0, 0]
rotate_around_origin(vec, how_much_rotation)

In [17]:
[0.02037104 0.02037104 0.05273125] == [0.02037104 0.02037104 0.05273125]

SyntaxError: invalid syntax (<ipython-input-17-915518408dfc>, line 1)

In [29]:
cubeb = 2 * np.array([0.02396875, 0.02396875, 0.057525])
cubeb

array([0.0479375, 0.0479375, 0.11505  ])

In [32]:
cubem = 2 * np.array([0.02037104, 0.02037104, 0.05273125])
cubem

array([0.04074208, 0.04074208, 0.1054625 ])

In [34]:
cylinderm = 2 * np.array([0.02127066, 0.02125045, 0.05500114])
cylinderm

array([0.04254132, 0.0425009 , 0.11000228])

In [27]:
0.001 * 10.5

0.0105

In [18]:
# logger loop

# copy from main experiment

"""
note: figure out how to render image in environment

1. do config shit
2. get all permutaations of simulator to go through
3. for each permuation: do the whole thing, log the whole thing.

4. 

"""

'\nnote: figure out how to render image in environment\n\n1. do config shit\n2. get all permutaations of simulator to go through\n3. for each permuation: do the whole thing, log the whole thing.\n\n4. \n\n'

In [3]:
import xml.etree.ElementTree as ET

In [4]:
# adjust these as input parameters
input_pos = [0.0, 0.0, 0.0]
input_euler = [1.57, 0.0, -1.57]

desired_pos = ' '.join([str(float_item) for float_item in input_pos])
desired_euler = ' '.join([str(float_item) for float_item in input_euler])


xml_filepath = '/home/jimzers/sim-to-real-kinova/src/sim-to-real-kinova-master/openai_gym_kinova/src/gym_kinova_gripper/envs/kinova_description/j2s7s300_end_effector_v1_CylinderM.xml'
# ASSUMPTIONS: ROOT IS FIRST BODY, THEN J2S7S300_LINK_7 IS THE NEXT FIRST NESTED BODY

tree = ET.parse(xml_filepath)
root = tree.getroot()

# according to assumptions, we find the wrist link.
j2s7s300_link_7_tag = root.find('worldbody').find('body').find('body')

# we then get the position and euler orientation
wrist_link_pos = j2s7s300_link_7_tag.attrib['pos']
wrist_link_euler_rot = j2s7s300_link_7_tag.attrib['euler']

# optional: access the current values.
wrist_link_pos_float_arr = [float(str_item) for str_item in wrist_link_pos.split()]
wrist_link_euler_rot_float_arr = [float(str_item) for str_item in wrist_link_euler_rot.split()]

# next, we modify them. we give an example here
j2s7s300_link_7_tag.set('pos', desired_pos)
j2s7s300_link_7_tag.set('euler', desired_euler)

# now, write to the xml file. and because we don't like keeping history, we'll just overwrite the existing file.
new_filepath = xml_filepath  # if you want to break the cycle, go ahead and change this variable

tree.write(new_filepath)

In [51]:
wrist_link_pos_float_arr = [float(str_item) for str_item in wrist_link_pos.split()]
wrist_link_euler_rot_float_arr = [float(str_item) for str_item in wrist_link_euler_rot.split()]

In [41]:
root_body = root.find('worldbody').find('body')
root_body.attrib

{'name': 'root', 'pos': '0 0 0'}

In [39]:
root_body = root.find('worldbody').find('body')

tmp_item = None
for item in root_body.findall('body'):
    tmp_item = itme

<Element 'body' at 0x7f43d2d7eb88>

In [46]:

j2s7s300_link_7_tag = root.find('worldbody').find('body').find('body')
j2s7s300_link_7_tag.attrib

{'name': 'j2s7s300_link_7', 'pos': '0.0 0.18 0.0654', 'euler': '-1.57 0 -1.57'}

In [47]:
wrist_link_pos = j2s7s300_link_7_tag.attrib['pos']
wrist_link_euler_rot = j2s7s300_link_7_tag.attrib['euler']


In [ ]:
j2s7s300_link_7_tag

In [30]:

mydoc = minidom.parse(xml_filepath)

In [16]:
from scipy.spatial.transform import Rotation as R

def rotate_around_origin(vec, how_much_rotation):
    # vec: xyz
    # how_much_rotation: in radians. use np.radians to covert if necessary
    # roll, pitch, yaw.
    rotation = R.from_euler('xyz', how_much_rotation)

    rotated_vec = rotation.apply(vec)
    return rotated_vec

In [17]:
rotate_around_origin([0,18,0.54], [0,0,0])

array([ 0.  , 18.  ,  0.54])

In [35]:
bruh = rotate_around_origin([-np.pi/2, 0, -np.pi/2], [0,0,0])
[0,18,0.54] => already in a world frame


array([-1.57079633,  0.        , -1.57079633])

In [ ]:
default_rotation = R.from_euler('xyz', [-np.pi/2, 0, -np.pi/2])

rotated_vec = rotation.apply(vec)

In [5]:
from scipy.spatial.transform import Rotation as R

test_vec = np.array([1, 1, 1])

# first add rotation noise
default_rotation = R.from_euler('xyz', [-np.pi/2, 0, -np.pi/2])

default_rotation.apply(test_vec)

# then add true rotation

# noise: add wrt to global frame?

# the actual translation:


array([ 1., -1., -1.])

In [7]:
import pandas as pd
df = pd.DataFrame(np.random.rand(5,2),index=range(0,10,2),columns=list('AB'))

In [13]:
df

A         B
0  0.285088  0.587229
2  0.996660  0.087878
4  0.889068  0.529402
6  0.000973  0.901505
8  0.392208  0.837493

In [21]:
df.iloc[4][['A', 'B']].to_numpy()

array([0.39220818, 0.83749272])

### simulator hell

In [ ]:
env.close()
# next: control hand position
roll_noise, pitch_noise, yaw_noise = 0, 0, 0

# roll_noise = np.pi / 6  # wrist go uppy/downy
# pitch_noise = np.pi / 6  # wrist pivot left/right
# yaw_noise = np.pi / 6  # rotate the wrist (wrist twist!!)

# -1.57, 0, -1.57 is the default hand position (for a side grasp)
start_hand_rotation = [-1.57 + roll_noise, 0 + pitch_noise, -1.57 + yaw_noise]
# start_hand_rotation = [0, , 0]

# mappings from start to eulers: 2 => x (1)
# 3 => 2

env = gym.make('gym_kinova_gripper:kinovagripper-v0')  # maybe just make a new one everytime lol

obs = env.reset(shape_keys=['CubeM'], hand_orientation='normal',
                start_pos=[0.0, 0.0, 0.053], hand_rotation=start_hand_rotation)  # TODO: make sure this is NO OBJECT
while True:
    env.render()

# note: simulator doesn't rotate around the point 0 0 0 either... we'll need to fix that

selecting object...
going into experiment function
EXPERIMENT FUNCTION before
{}
['CubeM']
EXPERIMENT FUNCTION
{'CubeM': '/kinova_description/j2s7s300_end_effector_v1_CubeM.xml'}
['CubeM']
hi, what could go wrong
FILENAME objects_file_to_list:  NONOfNOobjects.csv
shape keys: ['CubeM']
the filepath is: NONOfNOobjects.csv
THE FILENAME DOESNT EXIST
IM GENERATING LATIN SQUARES 1036
why the fuck am i entering self.experiment again
SHAPE KEYS: ['CubeM']
object keys: dict_keys(['CubeM'])
EXPERIMENT FUNCTION before
{'CubeM': '/kinova_description/j2s7s300_end_effector_v1_CubeM.xml'}
['CubeM']
EXPERIMENT FUNCTION
{'CubeM': '/kinova_description/j2s7s300_end_effector_v1_CubeM.xml'}
['CubeM']
TEMP <= N
TEMP <= N
TEMP <= N
TEMP <= N
TEMP <= N
TEMP <= N
TEMP <= N
TEMP <= N
TEMP <= N
NONOfNOobjects.csv
wtfwtf
wtfwtf
wtfwtf
wtfwtf
wtfwtf
wtfwtf
wtfwtf
wtfwtf
wtfwtf
get the object lol ==========
OUR RANDOM SHAPES BEFOREHAND
['CubeM', 'CubeM', 'CubeM', 'CubeM', 'CubeM', 'CubeM', 'CubeM', 'CubeM', 'CubeM'

In [ ]:

					<body name="j2s7s300_link_finger_1" pos="0.00279 0.03126 -0.11467" quat="0.379408 -0.662973 -0.245899 0.596699">


In [63]:
env.close()

lol


In [3]:
from scipy.spatial.transform import Rotation as R

In [ ]:
0.379408 -0.662973 -0.245899 0.596699

In [ ]:
                <body name="j2s7s300_link_finger_1" pos="0.00279 0.03126 -0.11467" quat="0.379408 -0.662973 -0.245899 0.596699">


In [36]:
urmom_bruh = R.from_quat([0.596699, 0.379408, -0.662973, -0.245899]).as_euler('XYZ')
urmom_bruh

array([ 1.57079924, -1.35961082, -2.49232776])

In [38]:
urmom_bruh[2] += np.pi/2
urmom_bruh

array([ 1.57079924, -1.35961082, -0.92153143])

In [18]:
quat_lol = R.from_euler('XYZ', urmom)

In [19]:
quat_lol.as_euler()

In [48]:
finger1_base = R.from_quat([0.596699, 0.379408, -0.662973, -0.245899]).as_euler('XYZ')
finger1_base

# TODO: try transforming back to quaternion?

array([ 1.57079924, -1.35961082, -2.49232776])

In [18]:
quat2euler([0.596699, 0.379408, -0.662973, -0.245899])

array([ 2.49232776, -1.35961082,  1.57079342])

In [49]:
finger1_base[2] += np.pi/12
finger1_base

array([ 1.57079924, -1.35961082, -2.23052837])

### mujoco is a bitch and all quats in mujoco are wxyz form.
scipy is xyzw form

In [4]:
finger2_base = R.from_quat([-0.254671, 0.659653, -0.37146, 0.601679]).as_euler('XYZ')
finger2_base[2] += np.pi/12
finger2_base

array([ 1.57079223,  1.3861396 , -2.23052714])

In [27]:
finger3_base = R.from_quat([-0.37146, 0.601679, -0.254671, 0.659653]).as_euler('XYZ')
finger3_base[2] += np.pi/12
finger3_base

array([-1.57080042,  1.3861396 ,  0.91106551])

In [29]:
np.pi/12

0.2617993877991494

In [17]:

# For testing whether a number is close to zero
_FLOAT_EPS = np.finfo(np.float64).eps
_EPS4 = _FLOAT_EPS * 4.0
def euler2mat(euler):
    """Convert Euler Angles to Rotation Matrix.  See rotation.py for notes"""
    euler = np.asarray(euler, dtype=np.float64)
    assert euler.shape[-1] == 3, "Invalid shaped euler {}".format(euler)

    ai, aj, ak = -euler[..., 2], -euler[..., 1], -euler[..., 0]
    si, sj, sk = np.sin(ai), np.sin(aj), np.sin(ak)
    ci, cj, ck = np.cos(ai), np.cos(aj), np.cos(ak)
    cc, cs = ci * ck, ci * sk
    sc, ss = si * ck, si * sk

    mat = np.empty(euler.shape[:-1] + (3, 3), dtype=np.float64)
    mat[..., 2, 2] = cj * ck
    mat[..., 2, 1] = sj * sc - cs
    mat[..., 2, 0] = sj * cc + ss
    mat[..., 1, 2] = cj * sk
    mat[..., 1, 1] = sj * ss + cc
    mat[..., 1, 0] = sj * cs - sc
    mat[..., 0, 2] = -sj
    mat[..., 0, 1] = cj * si
    mat[..., 0, 0] = cj * ci
    return mat


def euler2quat(euler):
    """Convert Euler Angles to Quaternions.  See rotation.py for notes"""
    euler = np.asarray(euler, dtype=np.float64)
    assert euler.shape[-1] == 3, "Invalid shape euler {}".format(euler)

    ai, aj, ak = euler[..., 2] / 2, -euler[..., 1] / 2, euler[..., 0] / 2
    si, sj, sk = np.sin(ai), np.sin(aj), np.sin(ak)
    ci, cj, ck = np.cos(ai), np.cos(aj), np.cos(ak)
    cc, cs = ci * ck, ci * sk
    sc, ss = si * ck, si * sk

    quat = np.empty(euler.shape[:-1] + (4,), dtype=np.float64)
    quat[..., 0] = cj * cc + sj * ss
    quat[..., 3] = cj * sc - sj * cs
    quat[..., 2] = -(cj * ss + sj * cc)
    quat[..., 1] = cj * cs - sj * sc
    return quat


def mat2euler(mat):
    """Convert Rotation Matrix to Euler Angles.  See rotation.py for notes"""
    mat = np.asarray(mat, dtype=np.float64)
    assert mat.shape[-2:] == (3, 3), "Invalid shape matrix {}".format(mat)

    cy = np.sqrt(mat[..., 2, 2] * mat[..., 2, 2] + mat[..., 1, 2] * mat[..., 1, 2])
    condition = cy > _EPS4
    euler = np.empty(mat.shape[:-1], dtype=np.float64)
    euler[..., 2] = np.where(
        condition,
        -np.arctan2(mat[..., 0, 1], mat[..., 0, 0]),
        -np.arctan2(-mat[..., 1, 0], mat[..., 1, 1]),
    )
    euler[..., 1] = np.where(
        condition, -np.arctan2(-mat[..., 0, 2], cy), -np.arctan2(-mat[..., 0, 2], cy)
    )
    euler[..., 0] = np.where(
        condition, -np.arctan2(mat[..., 1, 2], mat[..., 2, 2]), 0.0
    )
    return euler


def mat2quat(mat):
    """Convert Rotation Matrix to Quaternion.  See rotation.py for notes"""
    mat = np.asarray(mat, dtype=np.float64)
    assert mat.shape[-2:] == (3, 3), "Invalid shape matrix {}".format(mat)

    Qxx, Qyx, Qzx = mat[..., 0, 0], mat[..., 0, 1], mat[..., 0, 2]
    Qxy, Qyy, Qzy = mat[..., 1, 0], mat[..., 1, 1], mat[..., 1, 2]
    Qxz, Qyz, Qzz = mat[..., 2, 0], mat[..., 2, 1], mat[..., 2, 2]
    # Fill only lower half of symmetric matrix
    K = np.zeros(mat.shape[:-2] + (4, 4), dtype=np.float64)
    K[..., 0, 0] = Qxx - Qyy - Qzz
    K[..., 1, 0] = Qyx + Qxy
    K[..., 1, 1] = Qyy - Qxx - Qzz
    K[..., 2, 0] = Qzx + Qxz
    K[..., 2, 1] = Qzy + Qyz
    K[..., 2, 2] = Qzz - Qxx - Qyy
    K[..., 3, 0] = Qyz - Qzy
    K[..., 3, 1] = Qzx - Qxz
    K[..., 3, 2] = Qxy - Qyx
    K[..., 3, 3] = Qxx + Qyy + Qzz
    K /= 3.0
    # TODO: vectorize this -- probably could be made faster
    q = np.empty(K.shape[:-2] + (4,))
    it = np.nditer(q[..., 0], flags=["multi_index"])
    while not it.finished:
        # Use Hermitian eigenvectors, values for speed
        vals, vecs = np.linalg.eigh(K[it.multi_index])
        # Select largest eigenvector, reorder to w,x,y,z quaternion
        q[it.multi_index] = vecs[[3, 0, 1, 2], np.argmax(vals)]
        # Prefer quaternion with positive w
        # (q * -1 corresponds to same rotation as q)
        if q[it.multi_index][0] < 0:
            q[it.multi_index] *= -1
        it.iternext()
    return q


def quat2euler(quat):
    """Convert Quaternion to Euler Angles.  See rotation.py for notes"""
    return mat2euler(quat2mat(quat))


def subtract_euler(e1, e2):
    assert e1.shape == e2.shape
    assert e1.shape[-1] == 3
    q1 = euler2quat(e1)
    q2 = euler2quat(e2)
    q_diff = quat_mul(q1, quat_conjugate(q2))
    return quat2euler(q_diff)


def quat2mat(quat):
    """Convert Quaternion to Euler Angles.  See rotation.py for notes"""
    quat = np.asarray(quat, dtype=np.float64)
    assert quat.shape[-1] == 4, "Invalid shape quat {}".format(quat)

    w, x, y, z = quat[..., 0], quat[..., 1], quat[..., 2], quat[..., 3]
    Nq = np.sum(quat * quat, axis=-1)
    s = 2.0 / Nq
    X, Y, Z = x * s, y * s, z * s
    wX, wY, wZ = w * X, w * Y, w * Z
    xX, xY, xZ = x * X, x * Y, x * Z
    yY, yZ, zZ = y * Y, y * Z, z * Z

    mat = np.empty(quat.shape[:-1] + (3, 3), dtype=np.float64)
    mat[..., 0, 0] = 1.0 - (yY + zZ)
    mat[..., 0, 1] = xY - wZ
    mat[..., 0, 2] = xZ + wY
    mat[..., 1, 0] = xY + wZ
    mat[..., 1, 1] = 1.0 - (xX + zZ)
    mat[..., 1, 2] = yZ - wX
    mat[..., 2, 0] = xZ - wY
    mat[..., 2, 1] = yZ + wX
    mat[..., 2, 2] = 1.0 - (xX + yY)
    return np.where((Nq > _FLOAT_EPS)[..., np.newaxis, np.newaxis], mat, np.eye(3))


def quat_conjugate(q):
    inv_q = -q
    inv_q[..., 0] *= -1
    return inv_q


def quat_mul(q0, q1):
    assert q0.shape == q1.shape
    assert q0.shape[-1] == 4
    assert q1.shape[-1] == 4

    w0 = q0[..., 0]
    x0 = q0[..., 1]
    y0 = q0[..., 2]
    z0 = q0[..., 3]

    w1 = q1[..., 0]
    x1 = q1[..., 1]
    y1 = q1[..., 2]
    z1 = q1[..., 3]

    w = w0 * w1 - x0 * x1 - y0 * y1 - z0 * z1
    x = w0 * x1 + x0 * w1 + y0 * z1 - z0 * y1
    y = w0 * y1 + y0 * w1 + z0 * x1 - x0 * z1
    z = w0 * z1 + z0 * w1 + x0 * y1 - y0 * x1
    q = np.array([w, x, y, z])
    if q.ndim == 2:
        q = q.swapaxes(0, 1)
    assert q.shape == q0.shape
    return q


def quat_rot_vec(q, v0):
    q_v0 = np.array([0, v0[0], v0[1], v0[2]])
    q_v = quat_mul(q, quat_mul(q_v0, quat_conjugate(q)))
    v = q_v[1:]
    return v


def quat_identity():
    return np.array([1, 0, 0, 0])


def quat2axisangle(quat):
    theta = 0
    axis = np.array([0, 0, 1])
    sin_theta = np.linalg.norm(quat[1:])

    if sin_theta > 0.0001:
        theta = 2 * np.arcsin(sin_theta)
        theta *= 1 if quat[0] >= 0 else -1
        axis = quat[1:] / sin_theta

    return axis, theta


def euler2point_euler(euler):
    _euler = euler.copy()
    if len(_euler.shape) < 2:
        _euler = np.expand_dims(_euler, 0)
    assert _euler.shape[1] == 3
    _euler_sin = np.sin(_euler)
    _euler_cos = np.cos(_euler)
    return np.concatenate([_euler_sin, _euler_cos], axis=-1)


def point_euler2euler(euler):
    _euler = euler.copy()
    if len(_euler.shape) < 2:
        _euler = np.expand_dims(_euler, 0)
    assert _euler.shape[1] == 6
    angle = np.arctan(_euler[..., :3] / _euler[..., 3:])
    angle[_euler[..., 3:] < 0] += np.pi
    return angle


def quat2point_quat(quat):
    # Should be in qw, qx, qy, qz
    _quat = quat.copy()
    if len(_quat.shape) < 2:
        _quat = np.expand_dims(_quat, 0)
    assert _quat.shape[1] == 4
    angle = np.arccos(_quat[:, [0]]) * 2
    xyz = _quat[:, 1:]
    xyz[np.squeeze(np.abs(np.sin(angle / 2))) >= 1e-5] = (xyz / np.sin(angle / 2))[
        np.squeeze(np.abs(np.sin(angle / 2))) >= 1e-5
    ]
    return np.concatenate([np.sin(angle), np.cos(angle), xyz], axis=-1)


def point_quat2quat(quat):
    _quat = quat.copy()
    if len(_quat.shape) < 2:
        _quat = np.expand_dims(_quat, 0)
    assert _quat.shape[1] == 5
    angle = np.arctan(_quat[:, [0]] / _quat[:, [1]])
    qw = np.cos(angle / 2)

    qxyz = _quat[:, 2:]
    qxyz[np.squeeze(np.abs(np.sin(angle / 2))) >= 1e-5] = (qxyz * np.sin(angle / 2))[
        np.squeeze(np.abs(np.sin(angle / 2))) >= 1e-5
    ]
    return np.concatenate([qw, qxyz], axis=-1)


def normalize_angles(angles):
    """Puts angles in [-pi, pi] range."""
    angles = angles.copy()
    if angles.size > 0:
        angles = (angles + np.pi) % (2 * np.pi) - np.pi
        assert -np.pi - 1e-6 <= angles.min() and angles.max() <= np.pi + 1e-6
    return angles


def round_to_straight_angles(angles):
    """Returns closest angle modulo 90 degrees"""
    angles = np.round(angles / (np.pi / 2)) * (np.pi / 2)
    return normalize_angles(angles)


def get_parallel_rotations():
    mult90 = [0, np.pi / 2, -np.pi / 2, np.pi]
    parallel_rotations = []
    for euler in itertools.product(mult90, repeat=3):
        canonical = mat2euler(euler2mat(euler))
        canonical = np.round(canonical / (np.pi / 2))
        if canonical[0] == -2:
            canonical[0] = 2
        if canonical[2] == -2:
            canonical[2] = 2
        canonical *= np.pi / 2
        if all([(canonical != rot).any() for rot in parallel_rotations]):
            parallel_rotations += [canonical]
    assert len(parallel_rotations) == 24
    return parallel_rotations