In [2]:
%config IPCompleter.use_jedi = False

In [1]:
import numpy as np

In [14]:
bruh = np.load('sim_positional_test_v5_constant/episodes/obs_001.npy')
bruh[:, [33, 34, 35]]

array([[0.02037104, 0.02037104, 0.1054625 ],
       [0.02037104, 0.02037104, 0.1054625 ],
       [0.02037104, 0.02037104, 0.1054625 ],
       [0.02037104, 0.02037104, 0.1054625 ],
       [0.02037104, 0.02037104, 0.1054625 ],
       [0.02037104, 0.02037104, 0.1054625 ],
       [0.02037104, 0.02037104, 0.1054625 ],
       [0.02037104, 0.02037104, 0.1054625 ],
       [0.02037104, 0.02037104, 0.1054625 ],
       [0.02037104, 0.02037104, 0.1054625 ],
       [0.02037104, 0.02037104, 0.1054625 ],
       [0.02037104, 0.02037104, 0.1054625 ],
       [0.02037104, 0.02037104, 0.1054625 ],
       [0.02037104, 0.02037104, 0.1054625 ],
       [0.02037104, 0.02037104, 0.1054625 ],
       [0.02037104, 0.02037104, 0.1054625 ],
       [0.02037104, 0.02037104, 0.1054625 ],
       [0.02037104, 0.02037104, 0.1054625 ],
       [0.02037104, 0.02037104, 0.1054625 ],
       [0.02037104, 0.02037104, 0.1054625 ],
       [0.02037104, 0.02037104, 0.1054625 ],
       [0.02037104, 0.02037104, 0.1054625 ],
       [0.

In [11]:
bruh = np.load('sim_rl_v2/episodes/obs_001.npy')
bruh[:, [33, 34, 35]]

array([[0.03180836, 0.03187125, 0.13553753],
       [0.03180836, 0.03187125, 0.13553753],
       [0.03180836, 0.03187125, 0.13553753],
       [0.03180836, 0.03187125, 0.13553753],
       [0.03180836, 0.03187125, 0.13553753],
       [0.03180836, 0.03187125, 0.13553753],
       [0.03180836, 0.03187125, 0.13553753],
       [0.03180836, 0.03187125, 0.13553753],
       [0.03180836, 0.03187125, 0.13553753],
       [0.03180836, 0.03187125, 0.13553753],
       [0.03180836, 0.03187125, 0.13553753],
       [0.03180836, 0.03187125, 0.13553753],
       [0.03180836, 0.03187125, 0.13553753],
       [0.03180836, 0.03187125, 0.13553753],
       [0.03180836, 0.03187125, 0.13553753],
       [0.03180836, 0.03187125, 0.13553753],
       [0.03180836, 0.03187125, 0.13553753],
       [0.03180836, 0.03187125, 0.13553753],
       [0.03180836, 0.03187125, 0.13553753],
       [0.03180836, 0.03187125, 0.13553753],
       [0.03180836, 0.03187125, 0.13553753],
       [0.03180836, 0.03187125, 0.13553753],
       [0.

In [17]:
[0.03180836 * 2, 0.03187125 * 2, 0.13553753]

[0.06361672, 0.0637425, 0.13553753]

In [12]:
bruh = np.load('sim_rl_v2_cone/episodes/obs_001.npy')
bruh[:, [33, 34, 35]]

array([[0.03180836, 0.03187125, 0.13553753],
       [0.03180836, 0.03187125, 0.13553753],
       [0.03180836, 0.03187125, 0.13553753],
       [0.03180836, 0.03187125, 0.13553753],
       [0.03180836, 0.03187125, 0.13553753],
       [0.03180836, 0.03187125, 0.13553753],
       [0.03180836, 0.03187125, 0.13553753],
       [0.03180836, 0.03187125, 0.13553753],
       [0.03180836, 0.03187125, 0.13553753],
       [0.03180836, 0.03187125, 0.13553753],
       [0.03180836, 0.03187125, 0.13553753],
       [0.03180836, 0.03187125, 0.13553753],
       [0.03180836, 0.03187125, 0.13553753],
       [0.03180836, 0.03187125, 0.13553753],
       [0.03180836, 0.03187125, 0.13553753],
       [0.03180836, 0.03187125, 0.13553753],
       [0.03180836, 0.03187125, 0.13553753],
       [0.03180836, 0.03187125, 0.13553753],
       [0.03180836, 0.03187125, 0.13553753],
       [0.03180836, 0.03187125, 0.13553753],
       [0.03180836, 0.03187125, 0.13553753],
       [0.03180836, 0.03187125, 0.13553753],
       [0.

In [13]:
bruh = np.load('sim_rl_v2_vase/episodes/obs_001.npy')
bruh[:, [33, 34, 35]]

array([[0.02128863, 0.02125081, 0.11000255],
       [0.02128863, 0.02125081, 0.11000255],
       [0.02128863, 0.02125081, 0.11000255],
       [0.02128863, 0.02125081, 0.11000255],
       [0.02128863, 0.02125081, 0.11000255],
       [0.02128863, 0.02125081, 0.11000255],
       [0.02128863, 0.02125081, 0.11000255],
       [0.02128863, 0.02125081, 0.11000255],
       [0.02128863, 0.02125081, 0.11000255],
       [0.02128863, 0.02125081, 0.11000255],
       [0.02128863, 0.02125081, 0.11000255],
       [0.02128863, 0.02125081, 0.11000255],
       [0.02128863, 0.02125081, 0.11000255],
       [0.02128863, 0.02125081, 0.11000255],
       [0.02128863, 0.02125081, 0.11000255],
       [0.02128863, 0.02125081, 0.11000255],
       [0.02128863, 0.02125081, 0.11000255],
       [0.02128863, 0.02125081, 0.11000255],
       [0.02128863, 0.02125081, 0.11000255],
       [0.02128863, 0.02125081, 0.11000255],
       [0.02128863, 0.02125081, 0.11000255],
       [0.02128863, 0.02125081, 0.11000255],
       [0.

In [5]:
bruh = np.load('sim_rl_v2_cone/')

array([-3.22841866e-02,  2.66200262e-02,  2.57079771e-03,  3.90073338e-02,
        2.31347682e-02,  2.44893463e-02,  4.04570587e-02,  2.20662504e-02,
       -2.47608322e-02, -1.44959175e-02,  5.95175857e-02,  6.38397568e-03,
        4.20293069e-02,  6.04515407e-02,  2.50541033e-02,  4.70341656e-02,
        5.88283640e-02, -2.59889784e-02,  0.00000000e+00, -1.07064965e-18,
        0.00000000e+00,  2.08188864e-02,  7.35833820e-02, -3.77265814e-02,
       -2.47383612e-04, -3.66283306e-04,  1.50774177e-02,  9.79879761e-01,
        7.03860726e-01,  6.20956404e-01,  4.88293842e-01,  3.51200189e-01,
        3.09765128e-01,  3.18083577e-02,  3.18712518e-02,  1.35537535e-01,
        7.26429340e-02,  7.97012123e-02,  7.38901834e-02,  7.89206088e-02,
        4.49953532e-02,  5.30906705e-02,  5.17535955e-02,  5.47265227e-02,
        6.33165700e-02,  6.41253332e-02,  2.51207786e-02,  2.62115180e-02,
        4.73760018e-01,  2.75722866e-01,  6.63624779e-02,  7.01824525e-02,
        6.25556013e-02,  